### ISSUE TITLE
Add setup.py and distribute on PYPI

### ISSUE THREAD

**Issue by pydanny** [koslib/django-pwned-password#1]
If you need any help, you can use https://github.com/pydanny/cookiecutter-djangopackage or I can lend a hand.

**Comment by pydanny** [comment]
Nevermind, on second thought transmitting a password in the clear this way compresses a security hole.

**Comment by koslib** [comment]
@pydanny changed it to use range instead of plain text password, it's considered much better than divulging the user password to a 3rd-party.
